### ISSUE TITLE
Enable reuse of edition number parts (major, minor, patch), potentially encoding them separately

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#109]
Requested by @RohdeBSH of the IHO S-102 team (doc: https://github.com/iho-ohi/S-102-Product-Specification).

Right now the metadata portion looks like this:
```adoc
= Bathymetric Surface Product Specification
:series: S
:docnumber: 102
:edition: 2.2.0
```

The `edition` number is entered as a whole.

In IHO documents, the edition number parts (major, minor and patch) are often reused inside the document independently. Right now there is no way to individually reproduce these edition number parts.

Ways this can be accomplished:
* encode the edition number using separate metadata fields
* encode the edition number as current, split the number into separate edition parts allowing the attributes to be referenced inside the document

**Comment by opoudjis** [comment]
> encode the edition number using separate metadata fields
> encode the edition number as current, split the number into separate edition parts allowing the attributes to be referenced inside the document

I would prefer the latter, but if the edition part is being referenced by document attribute, that means I have to create new document attributes on the fly to be resolved. The Asciidoctor processing model *might* be made to do this, but if it does, it will be so clumsy, we'll wish it didn't.

So, we will allow both `:edition:`, and `:edition-major:`, `:edition-minor:`, `:edition-patch:`. If the latter group of attributes is present, they will be used instead of `:edition:`.
